# Generated by Django 5.1.3 on 2024-11-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_ad', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('description', models.TextField(blank=True, verbose_name='Product description')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is product visivle on website')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
