# Generated by Django 5.1.3 on 2024-11-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
